import streamlit as st
import pandas as pd
from data_processor import load_statement, get_summary
from categorizer import categorize_transactions
from visualizer import spending_by_category_chart, spending_over_time_chart,top_expenses_chart
from recommender import get_recommendations